apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-cronjob
spec:
  schedule: "0 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloworld
            image: dorbar7/helloworld
            env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: helloworld-config
                  key: WELCOME_MESSAGE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: helloworld-secret
                  key: API_KEY
            volumeMounts:
            - name: app-data
              mountPath: /app/data
          restartPolicy: OnFailure
          volumes:
          - name: app-data
            persistentVolumeClaim:
              claimName: helloworld-pvc
